version: "3.8"

networks:
  internal:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./laravel:/var/www/laravel
    depends_on:
      - laravel
      - supervisor
      - mariadb
      - pma
    networks:
      - internal
  laravel:
    ports:
      - "8080:8080"
    build:
      context: docker_files
      dockerfile: php.Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    networks:
      - internal
  supervisor:
    build:
      context: .
      dockerfile: docker_files/supervisor.dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    networks:
      - internal
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./env/db.env
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - internal
  pma:
    image: phpmyadmin
    env_file:
      - ./env/db.env
    links:
      - mariadb
    depends_on:
      - mariadb
      - laravel
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - 8888:80
    networks:
    - internal
  # vue:
  #   build:
  #     context: resources/frontend/app
  #     dockerfile: vue.Dockerfile
  #   volumes:
  #     - ./resources/frontend/app:/app
  #     - /app/node_modules
  #   ports:
  #     - '8010:8080'
  #   networks:
  #     - internal
  composer:
    build:
      context: docker_files
      dockerfile: composer.Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    networks:
      - internal
  artisan:
    build:
      context: docker_files
      dockerfile: php.Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]
    networks:
      - internal