version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./laravel:/var/www/laravel
    depends_on:
      - laravel
      - mariadb
    networks:
      - internal
  laravel:
    build:
      context: docker_files
      dockerfile: php.Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    networks:
      - internal
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./env/db.env
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - internal

  composer:
    build:
      context: docker_files
      dockerfile: composer.Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
  artisan:
    build:
      context: docker_files
      dockerfile: php.Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

networks:
  internal:
    driver: bridge